Can stm32
OxidosAutomotive/tock pull request #1
Opened 2022-10-12 17:09 UTC by teonaseverin

### Pull Request Overview

This pull request adds a CAN HIL, a CAN capsule and a low-level driver for STM32F4xx chips.

### Testing Strategy

This pull request was tested on a NUCLEO-F429ZI board.

### Documentation Updated

- [ ] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

2022-10-13 13:05 UTC, alexandruradovici commented on capsules/src/can.rs
> +pub struct App<> {
```suggestion
pub struct App {
```

2022-10-13 13:07 UTC, alexandruradovici commented on capsules/src/can.rs
> +    apps: Grant<App, UpcallCount<5>, AllowRoCount<1>, AllowRwCount<1>>,
Define some constants explaining what upcalls mean. Ideally something like 
```rust
mod upcalls {
  const UPCALL_PURPOSE_1: usize = 0;
  const UPCALL_POURPOSE_2: usize = 1;
  // ..
  const COUNT: usize = 5;
}
```

2022-10-13 13:09 UTC, alexandruradovici commented on capsules/src/can.rs
> +        grant: Grant<App, UpcallCount<5>, AllowRoCount<1>, AllowRwCount<1>>,
```suggestion
        grant: Grant<App, UpcallCount<upcalls::COUNT>, AllowRoCount<1>, AllowRwCount<1>>,
```

2022-10-13 13:10 UTC, alexandruradovici commented on capsules/src/can.rs
> +    fn schedule_callback(&self, callback_number: usize, data1: usize, data2: usize, data3: usize) {
```suggestion
    fn schedule_callback(&self, callback_number: usize, data: (usize, usize, usize)) {
```

2022-10-13 13:11 UTC, alexandruradovici commented on capsules/src/can.rs
> +        self.appid.map(|appid| {
```suggestion
        self.appid.map(|processid| {
```

2022-10-13 13:12 UTC, alexandruradovici commented on capsules/src/can.rs
> +            0 => CommandReturn::success_u32(self.can.receive_fifo_count() as u32),
We do not use any FIFOs anymore, just return success.

2022-10-13 13:13 UTC, alexandruradovici commented on capsules/src/can.rs
> +            // Calculate the timing parameters based on a given bitrate
```suggestion
            // Set the bitrate
```

2022-10-13 13:13 UTC, alexandruradovici commented on capsules/src/can.rs
> +            // Set the timing parameters
Add the set parameters at the end as an advanced feature.

Add a comment about the format of the two parameters. You can take a look at the touch driver.

2022-10-13 13:15 UTC, alexandruradovici commented on capsules/src/can.rs
> +                self.appid.set(appid);
Check if there is already a process that uses the driver and of there is any transfer in progress.

2022-10-13 13:15 UTC, alexandruradovici commented on capsules/src/can.rs
> +                self.appid.set(appid);
Check if there is already a process that uses the driver and of there is any transfer in progress.

2022-10-13 13:18 UTC, alexandruradovici commented on capsules/src/can.rs
> +                                }
Explain this in a comment. Why 16?

2022-10-13 13:18 UTC, alexandruradovici commented on capsules/src/can.rs
> +                self.appid.set(appid);
Verify if the process is using the driver.

2022-10-13 13:19 UTC, alexandruradovici commented on capsules/src/can.rs
> +            capsule_state.1 = capsule_state.1 + 1;
Why is this computed here?

2022-10-13 13:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +                            self.schedule_callback(2, ErrorCode::FAIL as usize, 0, 0)
Use the define constant.
```suggestion
                            self.schedule_callback(upcalls::UPCALL_MEANING_2, ErrorCode::FAIL as usize, 0, 0)
```

2022-10-13 13:21 UTC, alexandruradovici commented on capsules/src/can.rs
> +    wait_for_state: OptionalCell<(can::State, u8)>,
```suggestion
    wait_for_state_callback: OptionalCell<(can::State, u8)>,
```

2022-10-13 13:21 UTC, alexandruradovici commented on capsules/src/can.rs
> +                    None => todo!(),
What should be done here?

2022-10-13 13:22 UTC, alexandruradovici commented on capsules/src/can.rs
> +                                if driver_state.1 == 2 && peripheral_state == driver_state.0 {
```suggestion
                                if driver_state.1 == _use_a_constant_ && peripheral_state == driver_state.0 {
```

2022-10-13 13:23 UTC, alexandruradovici commented on capsules/src/can.rs
> +                self.schedule_callback(2, err as usize, 0, 0);
The buffer should be put back regardless whether the transmission errors or not.

2022-10-13 13:23 UTC, alexandruradovici commented on capsules/src/can.rs
> +                                        if user_buffer[0].get() == 0 {
Explain this in a comment referring the pull requests implementing the features that your are waiting for.

2022-10-13 13:25 UTC, alexandruradovici commented on capsules/src/can.rs
> +            Err(_) => todo!(),
What should be done here?

2022-10-13 13:26 UTC, alexandruradovici commented on capsules/src/can.rs
> +        match self.appid.map_or(Err(ErrorCode::NOMEM), |processid| {
The buffer is not put back.

Why do we copy data into the grant buffer?

2022-10-13 13:26 UTC, alexandruradovici commented on chips/stm32f4xx/src/can.rs
> +pub const BRP_MAX_STM32: u32 = 1023;
```suggestion
pub const BRP_MAX_STM32: u32 = 1023;

```

2022-10-13 13:27 UTC, alexandruradovici commented on chips/stm32f4xx/src/can.rs
> +#[repr(C)]
use `register_structs!`

2022-10-13 13:27 UTC, alexandruradovici commented on chips/stm32f4xx/src/can.rs
> +struct ReceiveMailBox {
use `register_structs!`

2022-10-13 13:28 UTC, alexandruradovici commented on chips/stm32f4xx/src/can.rs
> +#[allow(dead_code)]
Do we need these constants?

2022-10-13 13:29 UTC, alexandruradovici commented on chips/stm32f4xx/src/can.rs
> +        if let Err(inak_err) = Can::wait_for(20000, || self.registers.can_msr.is_set(CAN_MSR::INAK))
Explain this busy waiting, add the link to the documentation.

2022-10-13 13:30 UTC, alexandruradovici commented on chips/stm32f4xx/src/can.rs
> +        if let Some(client) = client {
Does this work? `self.controller_client.replace(client)?`

2022-10-13 13:31 UTC, alexandruradovici commented on kernel/src/hil/can.rs
> +impl Into<ErrorCode> for Error {
Add a comment with the error mapping.

2022-10-13 13:32 UTC, alexandruradovici commented on kernel/src/hil/can.rs
> +    /// This constant represents the synchronization segment and it is always
```suggestion
    /// This constant represents the synchronization segment.
```

2022-10-13 13:33 UTC, alexandruradovici commented on kernel/src/hil/can.rs
> +    /// 1 quantum long. It is used for the synchronization of the clocks.
```suggestion
    /// Most CAN devices seems to have define this in hardware to 1 quantum long. 
    /// It is used for the synchronization of the clocks.
```

2022-10-13 13:34 UTC, alexandruradovici commented on chips/stm32f4xx/src/can.rs
> +    fn wait_for(times: usize, f: impl Fn() -> bool) -> Result<(), kernel::ErrorCode> {
Please add a comment explaining the use of this function.

2022-10-13 13:35 UTC, alexandruradovici commented on chips/stm32f4xx/src/can.rs
> +        let filter_number = 0x00000001 << filter_info.number;
```suggestion
        let filter_number = 1 << filter_info.number;
```

2022-10-13 13:37 UTC, alexandruradovici commented on capsules/src/can.rs
> +        appid: ProcessId,
```suggestion
        processid: ProcessId,
```

2022-10-13 13:38 UTC, alexandruradovici commented on capsules/src/can.rs
> +//! Syscall driver capsule for CAN communication.
add a markdown file in `/docs` describing the API

2022-10-13 13:39 UTC, alexandruradovici commented on capsules/src/can.rs
> +                self.appid.set(appid);
Verify that process uses already the driver and that there is no other transfer.

2022-10-13 13:39 UTC, alexandruradovici commented on capsules/src/can.rs
> +                self.appid.set(appid);
Verify that process uses already the driver and that there is no other transfer.

2022-10-13 13:40 UTC, alexandruradovici commented on capsules/src/can.rs
> +                self.appid.set(appid);
Verify that this is the process that has enabled the driver.

2022-10-13 18:24 UTC, teonaseverin commented on chips/stm32f4xx/src/can.rs
> +        if let Some(client) = client {
no

2022-10-17 08:25 UTC, alexandruradovici commented on boards/components/src/can.rs
> +macro_rules! can_component_helper {
```suggestion
macro_rules! can_component_static {
```

2022-10-17 08:26 UTC, alexandruradovici commented on boards/components/src/can.rs
> +pub static mut CAN_RX_BUF: [u8; can::STANDARD_CAN_PACKET_SIZE] = [0; can::STANDARD_CAN_PACKET_SIZE];
Define these inside the macro, otherwise they are singleton and cannot be used in two separate instances.

2022-10-17 08:26 UTC, alexandruradovici commented on boards/components/src/can.rs
> +macro_rules! can_component_helper {
```suggestion
macro_rules! can_component_static {
```

2022-10-17 08:27 UTC, alexandruradovici commented on boards/nucleo_f429zi/Makefile
> +	$(error See README.md and update this section accordingly)
```suggestion
	$(error See README.md and update this section accordingly)

```

2022-10-17 08:27 UTC, alexandruradovici commented on boards/components/src/can.rs
> +use capsules::can::CanCapsule;
Add usage documentation.

2022-10-17 08:29 UTC, alexandruradovici commented on capsules/src/can.rs
> +//!
```suggestion
//! Author: Teona Severin <teona.severin@oxidos.io>
//!
```

2022-10-17 13:50 UTC, teonaseverin commented on capsules/src/can.rs
> +//!
The `kernel/src/hil/can.rs` file already has a copyright, should I change it too?

2022-10-17 17:20 UTC, alexandruradovici requested changes

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +//! let grant_can = self.board_kernel.create_grant(self.driver_num, &grant_cap);
```suggestion
//! let grant_can = self.board_kernel.create_grant(capsules::can::CanCapsule::DRIVER_NUM, &grant_cap);
```

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +//! kernel::hil::can::Receive::set_client(self.can, Some(can));
```suggestion
//! kernel::hil::can::Controller::set_client(can_peripheral, Some(can));
//! kernel::hil::can::Transmit::set_client(can_peripheral, Some(can));
//! kernel::hil::can::Receive::set_client(can_peripheral, Some(can));
```

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +    // callbacks must be called. It it used It is used to reflect
```suggestion
    // callbacks must be called. It is used to reflect
```

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +    // to the low-level hardware, in order for it to be sent on the bus.
```suggestion
    /// This function makes a copy of the buffer in the grant and sends it
    /// to the low-level hardware, in order for it to be sent on the bus.
```

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +    pub fn is_valid_app(&self, processid: ProcessId) -> bool {
```suggestion
    pub fn is_valid_process(&self, processid: ProcessId) -> bool {
```

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +            if owning_app == &processid {
```suggestion
            if owning_process == &processid {
```

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +        self.processid.map_or(true, |owning_app| {
```suggestion
        self.processid.map_or(true, |owning_process| {
```

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +                        .set((can::State::Running, false));
Move into match within the success arm

2022-10-17 17:20 UTC, alexandruradovici commented on capsules/src/can.rs
> +                        .set((can::State::Disabled, false));
Move into match in the success arm.

2022-10-17 17:20 UTC, alexandruradovici commented on kernel/src/hil/can.rs
> +    fn enabled(&self, status: Result<State, ErrorCode>);
```suggestion
    fn enabled(&self, status: Result<(), ErrorCode>);
```

2022-10-19 15:31 UTC, alexandruradovici requested changes

2022-10-19 15:31 UTC, alexandruradovici commented on boards/components/src/can.rs
> +//! Component for Can syscall interface.
```suggestion
//! Component for CAN syscall interface.
```

2022-10-19 15:31 UTC, alexandruradovici commented on boards/nucleo_f429zi/Makefile
> +APP=../../../libtock-c/examples/can_example/build/cortex-m4/cortex-m4.tbf
Reset the file to the original source

2022-10-19 15:31 UTC, alexandruradovici commented on capsules/src/can.rs
> +            },
Verify that the process owns it.

2022-10-19 15:31 UTC, alexandruradovici commented on capsules/src/can.rs
> +                }
Verify that the process owns it.

2022-10-19 15:31 UTC, alexandruradovici commented on capsules/src/can.rs
> +            }
Verify process

2022-10-19 15:31 UTC, alexandruradovici commented on capsules/src/can.rs
> +    // `enabled` for the `enable` command and `disabled` for the `disable` command).
```suggestion
```

2022-10-19 15:31 UTC, alexandruradovici commented on capsules/src/can.rs
> +    // error callback.
```suggestion
```

2022-10-19 15:31 UTC, alexandruradovici commented on capsules/src/can.rs
> +    // error callback.
```suggestion
```

2022-10-19 15:31 UTC, alexandruradovici commented on capsules/src/can.rs
> +    // was sent. This callback also makes an upcall to the userspace.
```suggestion
```

2022-10-19 15:31 UTC, alexandruradovici commented on capsules/src/can.rs
> +    // fifo.
```suggestion
```

2022-10-19 16:34 UTC, alexandruradovici approved these changes

2022-10-20 10:04 UTC, valexandru approved these changes

2022-10-20 10:05 UTC, alexandruradovici commented
bors r+

2022-10-20 10:32 UTC, merged